[package]
name = "item_store"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.46", features = ["full"] }
thiserror = "2.0"
mongodb = "3.2"
twox-hash = "2.0"
fastrand = "2.3"
